version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

# environment variables
environment:
  nodejs_version: "5"

# scripts that run after cloning repository
install:
  # install DNX
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - dnvm upgrade
  - dnu restore
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack  
  
# scripts to run before build
before_build:
  # install node modules
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install
  # run webpack with production flag
  - webpack -p
  # back to original folder
    
artifacts:
  # put whole folder into a zip file
  - path: Samples.Front\wwwroot